USE [DBKoperasiBuku]
GO

/****** Object:  Table [dbo].[BUKU]    Script Date: 02/14/2017 16:32:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BUKU](
	[BUKU_ID]
	[KODE_JENIS_BUKU] [varchar](4) NOT NULL,
	[TAHUN_PENERBIT] [date] NOT NULL,
	[KODE_BUKU] [varchar](5) NOT NULL,
	[NAMA_BUKU] [varchar](15) NOT NULL,
	[JML_HAL_BUKU] [int] NOT NULL,
 CONSTRAINT [PK_KODE_JENIS_BUKU] PRIMARY KEY CLUSTERED 
(
	[KODE_JENIS_BUKU] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


