--USE [MASTER]
--GO
--CREATE DATABASE [DBKoperasiBuku]
--ON PRIMARY
--(NAME=N'DBKoperasiBuku_DATA', FILENAME= N'C:\Batch102\DATA\DBKoperasiBuku_DATA.MDF')
--LOG ON
--(NAME=N'DBKoperasiBuku_LOG', FILENAME= N'C:\Batch102\LOG\DBKoperasiBuku_LOG.LDF')
--GO

--USE DBKoperasiBuku
--GO
--CREATE TABLE [MST].[PENGARANG]
--(
--	[PENGARANG_ID] [INT]IDENTITY (1,1) NOT NULL,
--	[KODE_PENGARANG] [VARCHAR](7) NOT NULL,
--	[NAMA] [VARCHAR] (30) NOT NULL,
--	[ALAMAT] [VARCHAR] (80) NOT NULL,
--	[KOTA] [VARCHAR] (15) NOT NULL,
--	[KELAMIN] [VARCHAR] (1) NOT NULL,
--	CONSTRAINT PK_PENGARANG_ID PRIMARY KEY (PENGARANG_ID)
--	)
--	GO

USE DBKoperasiBuku
GO
CREATE TABLE [MST].[GAJI]
(
	[GAJI_ID] [INT]IDENTITY (1,1) NOT NULL,
	[KODE_PENGARANG] [VARCHAR](7) NOT NULL,
	[NAMA] [VARCHAR] (30) NOT NULL,
	[GAJI] [DECIMAL] (18,4) NOT NULL,
	CONSTRAINT PK_GAJI_ID PRIMARY KEY (GAJI_ID)
	)
GO

USE DBKoperasiBuku
GO
CREATE TABLE [MST].[KODE_JENIS]
(
	[KODE_JENIS_ID] [INT]IDENTITY (1,1) NOT NULL,
	[KODE_JENIS] [VARCHAR](4) NOT NULL,
	[LAMA_PEMINJAMAN][INT] NOT NULL,
	[KETERANGAN] [VARCHAR] (30)NOT NULL,
	CONSTRAINT PK_KODE_JENIS_ID PRIMARY KEY (KODE_JENIS_ID)
	)
GO

USE DBKoperasiBuku
GO
CREATE TABLE [MST].[BUKU]
(
	[BUKU_ID] [INT]IDENTITY (1,1) NOT NULL,
	[KODE_JENIS] [VARCHAR](4) NOT NULL,
	[TAHUN_PENERBIT] [DATE] NOT NULL,
	[KODE_BUKU] [VARCHAR] (5) NOT NULL,
	[NAMA_BUKU] [VARCHAR] (15) NOT NULL,
	[JML_HAL_BUKU] [INT] NOT NULL,
	CONSTRAINT PK_BUKU_ID PRIMARY KEY (BUKU_ID) 
	)
GO

USE DBKoperasiBuku
GO
CREATE TABLE [MST].[PENERBIT]
(
	[PENERBIT_ID] [INT]IDENTITY (1,1) NOT NULL,
	[KODE_PENERBIT] [VARCHAR](5) NOT NULL,
	[NAMA_PENERBIT] [VARCHAR] (15) NOT NULL,
	[ALAMAT_PENERBIT] [VARCHAR] (15) NOT NULL
	CONSTRAINT PK_PENERBIT_ID PRIMARY KEY (PENERBIT_ID)
	)
GO

USE DBKoperasiBuku
GO
CREATE TABLE [TRX].[PEMINJAMAN]
(
	[PEMINJAMAN_ID] [INT]IDENTITY (1,1) NOT NULL,
	[KODE_PEMINJAMAN] [VARCHAR](5) NOT NULL,
	[TANGGAL_PINJAM] [DATE] NOT NULL,
	[KODE_BUKU] [VARCHAR] (5) NOT NULL
	CONSTRAINT PK_PEMINJAMAN_ID PRIMARY KEY (PEMINJAMAN_ID)
	)
GO
