//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waMVCDay12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUKU
    {
        public int BUKU_ID { get; set; }
        public string KODE_JENIS { get; set; }
        public System.DateTime TAHUN_PENERBIT { get; set; }
        public string KODE_BUKU { get; set; }
        public string NAMA_BUKU { get; set; }
        public int JML_HAL_BUKU { get; set; }
    }
}
