//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waMVCDay12.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBKoperasiBukuEntities : DbContext
    {
        public DBKoperasiBukuEntities()
            : base("name=DBKoperasiBukuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BUKU> BUKU { get; set; }
        public DbSet<GAJI> GAJI { get; set; }
        public DbSet<KODE_JENIS> KODE_JENIS { get; set; }
        public DbSet<PENERBIT> PENERBIT { get; set; }
        public DbSet<PENGARANG> PENGARANG { get; set; }
        public DbSet<PEMINJAMAN> PEMINJAMAN { get; set; }
    }
}
