//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waMVCDay12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAKULTAS
    {
        public int FAKULTAS_ID { get; set; }
        public string KODE_FAKULTAS { get; set; }
        public string NAMA_FAKULTAS { get; set; }
    }
}
