//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waMVCDay12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KODE_JENIS
    {
        public int KODE_JENIS_ID { get; set; }
        public string KODE_JENIS1 { get; set; }
        public int LAMA_PEMINJAMAN { get; set; }
        public string KETERANGAN { get; set; }
    }
}
