//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waMVCDay12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEMINJAMAN
    {
        public int PEMINJAMAN_ID { get; set; }
        public string KODE_PEMINJAMAN { get; set; }
        public System.DateTime TANGGAL_PINJAM { get; set; }
        public string KODE_BUKU { get; set; }
    }
}
